# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trivia Battle Game' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Trivia Battle Game
pod 'Google-Mobile-Ads-SDK'
end
